# -*- coding: utf-8 -*-
"""CART498_A1_Surreal_Collage

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hUIJBZUOaK68kj8K16KASG1d7uuSA7Af

You can install Python libraries in Colab using the `!pip install` command. The exclamation mark `!` at the beginning of the line tells Colab to execute the command as a shell command.
"""

import torch

print("PyTorch version:", torch.__version__)
print("GPU available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")

!pip install -U diffusers transformers accelerate safetensors

import diffusers
import transformers
import accelerate

print("Diffusers:", diffusers.__version__)
print("Transformers:", transformers.__version__)
print("Accelerate:", accelerate.__version__)

import torch
from diffusers import StableDiffusionPipeline

model_id = "stable-diffusion-v1-5/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16
)

pipe = pipe.to("cuda")

prompts = {
    "image1": "illustrated painting of a human mouth open wide, tiny pink flowers growing inside instead of teeth, bold flat colors, painterly illustration style, surreal",

    "image2": "illustrated painting of a human mouth open wide, a tiny bird sitting inside instead of teeth, bold flat colors, painterly illustration style, surreal",

    "image3": "illustrated painting of a human mouth open wide, tiny dark spiky thorns growing inside instead of teeth, bold flat colors, painterly illustration style, surreal"
}

negative_prompt = "photorealistic, 3D render, photograph, gore, blood, horror, scary, disturbing, text, watermark, blurry, low quality, deformed"

import os

os.makedirs("A1", exist_ok=True)

negative_prompt = "people, humans, text, typography, logos, watermark, blurry, deformed, extra limbs, low quality"

generator = torch.Generator("cuda").manual_seed(888)  # same seed = same visual "world"

for name, prompt in prompts.items():
    image = pipe(
        prompt,
        negative_prompt=negative_prompt,
        num_inference_steps=42,
        guidance_scale=8.8,
        generator=generator
    ).images[0]

    image.save(f"A1/{name}.jpg")

    with open(f"A1/{name}.txt", "w") as f:
        f.write(prompt)

print("Done! Check the A1 folder.")